language: python
python: 3.6

env:
  global:
    - SOLC_URL='https://github.com/ethereum/solidity/releases/download/v0.4.23/solc-static-linux'
    - SOLC_VERSION='v0.4.23'

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

before_install:
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - ./.travis/download_solc.sh

install:
  - pip install -r requirements-dev.txt

script:
  - make lint
  - make typecheck
  - make test
  - python setup.py develop

deploy:
  provider: pypi
  skip_cleanup: true
  user: raiden_pypi_automated
  password:
    secure: "tk1s9XFXDNsphxrBJ0SYna+RIwjqnjZd/6wrCZ/hy232o0B6ja8bedOMYW9pQQUeVgBC5PCH2/MN5MKVzse+u5f3fxC48as9H46vuIA8Y5LaGva0AjduiWOGfUXl3ndgnpdwUoXCydRRIDf32RtL/HGOPVv8hHdHwewyqg4FczF8CISWKZaKy4D8ParmuumLQ8qvlexJL/AMIVLBZ9dTbYfwsmouVJ3scNQ4zhgyCEG+u+VmECREzBmIcgI39YoA3UF+CVRtZM9V5Y7WrE0+W4nsjm1ON7HZlFmjlPAo1yivKrToxcTVfOdccEghCJYV6bTgC546sZOnJ65yiTuaW69coBeKGPQA61r7JEYNjj6BKxbJIRnX0AIuov8Ny2visK1PBY/rYJNVPPQn4Ov4DI/8T2RqNV+MXKLv8bcgtSR//5aTBVtP6kQfuTwn6zzEMvS9cqZSybU7BTmuuK/0h1yE0hm5S52eP7FOwRxaaQR49SbArCW2CR545KjMm0EcivVGq1D+Yzeqw3jXANytWspZqfjZK6IWTm8JkZFpxV161ojcZKe/6av1M4YmFn3eS4eoMb86yak1BfqwH1laQZipa4KvlVTQvdW0uY4hIhk3oQAtD+E3L8oBhFbsIXr6WrcZEKMPdI3hgWLIv5XELqKBZwPUqw6AlCtNjUosVkc="
  python: 3.6
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: raiden-network/raiden-libs
    branch: master
